<a href="https://colab.research.google.com/github/Shubh23104/Flight_Price_Prediction/blob/main/Flight_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
df_train = pd.read_excel('Data_Train.xlsx')
df_train.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [ ]:
df_train.shape

(10683, 11)

In [ ]:
df_test = pd.read_excel('Test_set.xlsx')
df_test.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [ ]:
df_test.shape

(2671, 10)

In [ ]:
final_df = pd.concat([df_train,df_test],axis = 0)
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [ ]:
final_df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
2666,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN
2667,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN
2668,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
2669,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
2670,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [ ]:
final_df.shape

(13354, 11)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.7+ MB

## ***Feature Engineering Process***

In [ ]:
# handling Date time Feature
final_df['Date'] = [feature for feature in final_df['Date_of_Journey'].str.split('/').str[0]]
final_df['Month'] = [feature for feature in final_df['Date_of_Journey'].str.split('/').str[1]]
final_df['Year'] = [feature for feature in final_df['Date_of_Journey'].str.split('/').str[2]]

In [ ]:
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,01,03,2019

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
 11  Date             13354 non-null  object
 12  Month            13354 non-null  object
 13  Year             13354 non-null  object
dtypes: float64(1), object(13)
memory usage: 2.0+ MB

In [ ]:
final_df['Date'] = final_df['Date'].astype(int)
final_df['Month'] = final_df['Month'].astype(int)
final_df['Year'] = final_df['Year'].astype(int)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
 11  Date             13354 non-null  int64
 12  Month            13354 non-null  int64
 13  Year             13354 non-null  int64
dtypes: float64(1), int64(3), object(10)
memory usage: 2.0+ MB

In [ ]:
final_df = final_df.drop(['Date_of_Journey'],axis=1)

In [ ]:
final_df.head(3)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,6,2019

In [ ]:
# Handling Arrival time Category
final_df['Arrival_Time'] = [feature for feature in final_df['Arrival_Time'].str.split(' ').str[0]]

In [ ]:
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019

In [ ]:
final_df.isnull().sum()

Airline               0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
Date                  0
Month                 0
Year                  0
dtype: int64

In [ ]:
final_df['Arrival_hour'] = [feature for feature in final_df['Arrival_Time'].str.split(':').str[0]]
final_df['Arrival_minute'] = [feature for feature in final_df['Arrival_Time'].str.split(':').str[1]]

In [ ]:
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35

In [ ]:
final_df['Arrival_hour'] = final_df['Arrival_hour'].astype(int)
final_df['Arrival_minute'] = final_df['Arrival_minute'].astype(int)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13354 non-null  object
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Month            13354 non-null  int64
 12  Year             13354 non-null  int64
 13  Arrival_hour     13354 non-null  int64
 14  Arrival_minute   13354 non-null  int64
dtypes: float64(1), int64(5), object(9)
memory usage: 2.1+ MB

In [ ]:
final_df.drop(['Arrival_Time'],axis=1,inplace=True)

In [ ]:
final_df.head(3)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882.0,9,6,2019,4,25

In [ ]:
# Handling Depature time Category
final_df['Dep_Time'] = [feature for feature in final_df['Dep_Time'].str.split(' ').str[0]]

In [ ]:
final_df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10

In [ ]:
final_df['Dept_hour'] = [feature for feature in final_df['Dep_Time'].str.split(':').str[0]]
final_df['Dept_minute'] = [feature for feature in final_df['Dep_Time'].str.split(':').str[1]]
final_df['Dept_hour'] = final_df['Dept_hour'].astype(int)
final_df['Dept_minute'] = final_df['Dept_minute'].astype(int)

In [ ]:
final_df.head(3)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882.0,9,6,2019,4,25,9,25

In [ ]:
final_df.drop(['Dep_Time'],axis=1,inplace=True)

In [ ]:
final_df.head(3)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882.0,9,6,2019,4,25,9,25

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13353 non-null  object
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int64
 9   Month            13354 non-null  int64
 10  Year             13354 non-null  int64
 11  Arrival_hour     13354 non-null  int64
 12  Arrival_minute   13354 non-null  int64
 13  Dept_hour        13354 non-null  int64
 14  Dept_minute      13354 non-null  int64
dtypes: float64(1), int64(7), object(7)
memory usage: 2.1+ MB

In [ ]:
final_df.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,5,50

In [ ]:
final_df.loc[final_df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480.0,6,5,2019,9,25,9,45

In [ ]:
# Handling Route and Total Stops Category
# But here I can See that route is similar to total stops so i can taken information from total stops and i can not require route feature
# but i can not drop it because stops are influence the price when number of stops are increse the price are incresed
final_df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [ ]:
final_df.loc[final_df['Total_Stops'] == 'nan']

Empty DataFrame
Columns: [Airline, Source, Destination, Route, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_hour, Arrival_minute, Dept_hour, Dept_minute]
Index: []

In [ ]:
final_df.loc[final_df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480.0,6,5,2019,9,25,9,45

In [ ]:
final_df['Total_Stops'] = final_df['Total_Stops'].map({'non-stop':0, '1 stop':1, '2 stops':2, '3 stops':3, '4 stops':4, 'nan':1})

In [ ]:
final_df.head(3)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25

In [ ]:
final_df.drop(['Route'],axis=1,inplace=True)

In [ ]:
final_df.head(3)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Duration         13354 non-null  object
 4   Total_Stops      13353 non-null  float64
 5   Additional_Info  13354 non-null  object
 6   Price            10683 non-null  float64
 7   Date             13354 non-null  int64
 8   Month            13354 non-null  int64
 9   Year             13354 non-null  int64
 10  Arrival_hour     13354 non-null  int64
 11  Arrival_minute   13354 non-null  int64
 12  Dept_hour        13354 non-null  int64
 13  Dept_minute      13354 non-null  int64
dtypes: float64(2), int64(7), object(5)
memory usage: 2.0+ MB

In [ ]:
# handling Additional info Category
final_df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [ ]:
final_df.replace({"Additional_Info":['No Info']}, {"Additional_Info":['No info']}, inplace=True)

In [ ]:
final_df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [ ]:
# Handling Duration Category
final_df['d_hour'] = [feature for feature in final_df['Duration'].str.split(' ').str[0].str.split('h').str[0]]

In [ ]:
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute,d_hour
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50,7
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25,19
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5,5
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50,4

In [ ]:
final_df['d_minute'] = [feature for feature in final_df['Duration'].str.split(' ').str[1].str.split('m').str[0]]

In [ ]:
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute,d_hour,d_minute
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25,19,NaN
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50,4,45

In [ ]:
final_df['d_minute'] = final_df['d_minute'].fillna(0)
final_df['d_minute'] = final_df['d_minute'].astype(int)

In [ ]:
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute,d_hour,d_minute
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50,4,45

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Duration         13354 non-null  object
 4   Total_Stops      13353 non-null  float64
 5   Additional_Info  13354 non-null  object
 6   Price            10683 non-null  float64
 7   Date             13354 non-null  int64
 8   Month            13354 non-null  int64
 9   Year             13354 non-null  int64
 10  Arrival_hour     13354 non-null  int64
 11  Arrival_minute   13354 non-null  int64
 12  Dept_hour        13354 non-null  int64
 13  Dept_minute      13354 non-null  int64
 14  d_hour           13354 non-null  object
 15  d_minute         13354 non-null  int64
dtypes: float64(2), int64(8), object(6)
memory usage: 2.2+ MB

In [ ]:
final_df['d_hour'].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', '5m', '41', '40'], dtype=object)

In [ ]:
final_df.replace({"d_hour":['5m']}, {"d_hour":['0']}, inplace=True)

In [ ]:
final_df['d_hour'] = final_df['d_hour'].astype(int)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Duration         13354 non-null  object
 4   Total_Stops      13353 non-null  float64
 5   Additional_Info  13354 non-null  object
 6   Price            10683 non-null  float64
 7   Date             13354 non-null  int64
 8   Month            13354 non-null  int64
 9   Year             13354 non-null  int64
 10  Arrival_hour     13354 non-null  int64
 11  Arrival_minute   13354 non-null  int64
 12  Dept_hour        13354 non-null  int64
 13  Dept_minute      13354 non-null  int64
 14  d_hour           13354 non-null  int64
 15  d_minute         13354 non-null  int64
dtypes: float64(2), int64(9), object(5)
memory usage: 2.2+ MB

In [ ]:
final_df.loc[final_df['d_hour'] == 0]

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute,d_hour,d_minute
6474,Air India,Mumbai,Hyderabad,5m,2.0,No info,17327.0,6,3,2019,16,55,16,50,0,0
2660,Air India,Mumbai,Hyderabad,5m,2.0,No info,NaN,12,3,2019,16,55,16,50,0,0

In [ ]:
final_df['Duration'] = (final_df['d_hour'] * 60) + final_df['d_minute']

In [ ]:
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute,d_hour,d_minute
0,IndiGo,Banglore,New Delhi,170,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,445,2.0,No info,7662.0,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,1140,2.0,No info,13882.0,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,325,1.0,No info,6218.0,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,285,1.0,No info,13302.0,1,3,2019,21,35,16,50,4,45

In [ ]:
final_df.loc[final_df['Duration'] == 0]

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute,d_hour,d_minute
6474,Air India,Mumbai,Hyderabad,0,2.0,No info,17327.0,6,3,2019,16,55,16,50,0,0
2660,Air India,Mumbai,Hyderabad,0,2.0,No info,NaN,12,3,2019,16,55,16,50,0,0

In [ ]:
final_df.replace({"Duration":[0]}, {"Duration":[5]}, inplace=True)

In [ ]:
final_df.loc[final_df['Duration'] == 5]

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute,d_hour,d_minute
6474,Air India,Mumbai,Hyderabad,5,2.0,No info,17327.0,6,3,2019,16,55,16,50,0,0
2660,Air India,Mumbai,Hyderabad,5,2.0,No info,NaN,12,3,2019,16,55,16,50,0,0

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Duration         13354 non-null  int64
 4   Total_Stops      13353 non-null  float64
 5   Additional_Info  13354 non-null  object
 6   Price            10683 non-null  float64
 7   Date             13354 non-null  int64
 8   Month            13354 non-null  int64
 9   Year             13354 non-null  int64
 10  Arrival_hour     13354 non-null  int64
 11  Arrival_minute   13354 non-null  int64
 12  Dept_hour        13354 non-null  int64
 13  Dept_minute      13354 non-null  int64
 14  d_hour           13354 non-null  int64
 15  d_minute         13354 non-null  int64
dtypes: float64(2), int64(10), object(4)
memory usage: 2.2+ MB

In [ ]:
final_df.drop(['d_hour'],axis=1,inplace=True)

In [ ]:
final_df.drop(['d_minute'],axis=1,inplace=True)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Duration         13354 non-null  int64
 4   Total_Stops      13353 non-null  float64
 5   Additional_Info  13354 non-null  object
 6   Price            10683 non-null  float64
 7   Date             13354 non-null  int64
 8   Month            13354 non-null  int64
 9   Year             13354 non-null  int64
 10  Arrival_hour     13354 non-null  int64
 11  Arrival_minute   13354 non-null  int64
 12  Dept_hour        13354 non-null  int64
 13  Dept_minute      13354 non-null  int64
dtypes: float64(2), int64(8), object(4)
memory usage: 2.0+ MB

In [ ]:
# Handling Airline, source, Destination and Additional info Category using label encoder or using OneHotEncoder by importing from sklearn library
final_df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [ ]:
# For one hot encoding
# from sklearn.preprocessing import OneHotEncoder
# ohe = OneHotEncoder()

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

In [ ]:
final_df['Airline'] = labelencoder.fit_transform(final_df['Airline'])
final_df['Source'] = labelencoder.fit_transform(final_df['Source'])
final_df['Destination'] = labelencoder.fit_transform(final_df['Destination'])
final_df['Additional_Info'] = labelencoder.fit_transform(final_df['Additional_Info'])

In [ ]:
final_df.shape

(13354, 14)

In [ ]:
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute
0,3,0,5,170,0.0,7,3897.0,24,3,2019,1,10,22,20
1,1,3,0,445,2.0,7,7662.0,1,5,2019,13,15,5,50
2,4,2,1,1140,2.0,7,13882.0,9,6,2019,4,25,9,25
3,3,3,0,325,1.0,7,6218.0,12,5,2019,23,30,18,5
4,3,0,5,285,1.0,7,13302.0,1,3,2019,21,35,16,50

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  int64
 1   Source           13354 non-null  int64
 2   Destination      13354 non-null  int64
 3   Duration         13354 non-null  int64
 4   Total_Stops      13353 non-null  float64
 5   Additional_Info  13354 non-null  int64
 6   Price            10683 non-null  float64
 7   Date             13354 non-null  int64
 8   Month            13354 non-null  int64
 9   Year             13354 non-null  int64
 10  Arrival_hour     13354 non-null  int64
 11  Arrival_minute   13354 non-null  int64
 12  Dept_hour        13354 non-null  int64
 13  Dept_minute      13354 non-null  int64
dtypes: float64(2), int64(12)
memory usage: 2.0 MB

In [ ]:
final_df.loc[final_df['Total_Stops'].isnull()]

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute
9039,1,2,1,1420,NaN,7,7480.0,6,5,2019,9,25,9,45

In [ ]:
final_df.head(10)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute
0,3,0,5,170,0.0,7,3897.0,24,3,2019,1,10,22,20
1,1,3,0,445,2.0,7,7662.0,1,5,2019,13,15,5,50
2,4,2,1,1140,2.0,7,13882.0,9,6,2019,4,25,9,25
3,3,3,0,325,1.0,7,6218.0,12,5,2019,23,30,18,5
4,3,0,5,285,1.0,7,13302.0,1,3,2019,21,35,16,50
5,8,3,0,145,0.0,7,3873.0,24,6,2019,11,25,9,0
6,4,0,5,930,1.0,5,11087.0,12,3,2019,10,25,18,55
7,4,0,5,1265,1.0,7,22270.0,1,3,2019,5,5,8,0
8,4,0,5,1530,1.0,5,11087.0,12,3,2019,10,25,8,55
9,6,2,1,470,1.0,7,8625.0,27,5,2019,19,15,11,25

In [ ]:
final_df['Total_Stops'] = np.where(final_df['Total_Stops'].isnull(),1,final_df['Total_Stops'])

In [ ]:
final_df.head(10)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dept_hour,Dept_minute
0,3,0,5,170,0.0,7,3897.0,24,3,2019,1,10,22,20
1,1,3,0,445,2.0,7,7662.0,1,5,2019,13,15,5,50
2,4,2,1,1140,2.0,7,13882.0,9,6,2019,4,25,9,25
3,3,3,0,325,1.0,7,6218.0,12,5,2019,23,30,18,5
4,3,0,5,285,1.0,7,13302.0,1,3,2019,21,35,16,50
5,8,3,0,145,0.0,7,3873.0,24,6,2019,11,25,9,0
6,4,0,5,930,1.0,5,11087.0,12,3,2019,10,25,18,55
7,4,0,5,1265,1.0,7,22270.0,1,3,2019,5,5,8,0
8,4,0,5,1530,1.0,5,11087.0,12,3,2019,10,25,8,55
9,6,2,1,470,1.0,7,8625.0,27,5,2019,19,15,11,25

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  int64
 1   Source           13354 non-null  int64
 2   Destination      13354 non-null  int64
 3   Duration         13354 non-null  int64
 4   Total_Stops      13354 non-null  float64
 5   Additional_Info  13354 non-null  int64
 6   Price            10683 non-null  float64
 7   Date             13354 non-null  int64
 8   Month            13354 non-null  int64
 9   Year             13354 non-null  int64
 10  Arrival_hour     13354 non-null  int64
 11  Arrival_minute   13354 non-null  int64
 12  Dept_hour        13354 non-null  int64
 13  Dept_minute      13354 non-null  int64
dtypes: float64(2), int64(12)
memory usage: 2.0 MB